import nodemailer from "nodemailer";
import type { ScanResult, Severity } from "./scan";
import { summarize, SEVERITY_META, FINDING_META } from "./report";
import { isValidTeamsWebhook } from "./security";

const SEVERITIES: Severity[] = ["critical", "high", "medium", "low"];

/* ------------------------------------------------------------ SMTP core --- */

/** Build a reusable SMTP transport from env (cPanel/Namecheap mailbox). */
function getTransport() {
  const host = process.env.SMTP_HOST;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  if (!host || !user || !pass) {
    throw new Error("Email is not configured (missing SMTP_HOST/USER/PASS).");
  }
  const port = Number(process.env.SMTP_PORT ?? 465);
  return nodemailer.createTransport({
    host,
    port,
    secure: port === 465, // 465 = implicit TLS; 587 = STARTTLS
    auth: { user, pass },
  });
}

export const MAIL_FROM =
  process.env.MAIL_FROM ?? "OverShare Check <reports@oversharecheck.com>";

/** Send a plain message via SMTP. Used by the waitlist route too. */
export async function sendMail(opts: {
  to: string;
  subject: string;
  html?: string;
  text?: string;
}): Promise<void> {
  const transport = getTransport();
  await transport.sendMail({ from: MAIL_FROM, ...opts });
}

/* ---------------------------------------------------------------- Email --- */

function reportHtml(result: ScanResult): string {
  const s = summarize(result);
  const gradeColor = { A: "#059669", B: "#65a30d", C: "#d97706", D: "#ea580c", F: "#dc2626" }[s.grade];
  const rows = result.findings
    .slice(0, 50)
    .map((f) => {
      const m = FINDING_META[f.type];
      const color = { critical: "#dc2626", high: "#ea580c", medium: "#d97706", low: "#64748b" }[f.severity];
      return `<tr>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;vertical-align:top">
          <span style="background:${color};color:#fff;font-size:11px;font-weight:600;text-transform:uppercase;padding:2px 6px;border-radius:4px">${SEVERITY_META[f.severity].label}</span>
        </td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0">
          <strong style="color:#0f172a">${m.title}</strong><br>
          <span style="color:#475569;font-size:13px">${escapeHtml(f.detail)}</span><br>
          <span style="color:#94a3b8;font-size:11px;word-break:break-all">${escapeHtml(f.path)}</span>
        </td>
      </tr>`;
    })
    .join("");

  const counts = SEVERITIES.map(
    (sev) => `${s.counts[sev]} ${SEVERITY_META[sev].label.toLowerCase()}`,
  ).join(" · ");

  return `<div style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:0 auto;color:#0f172a">
    <p style="color:#2563eb;font-size:12px;font-weight:600;text-transform:uppercase;margin:0">OverShare Check · Exposure Report</p>
    <table style="width:100%;margin-top:8px"><tr>
      <td><h1 style="margin:0;font-size:22px">${escapeHtml(result.siteName)}</h1>
        <p style="margin:4px 0 0;color:#64748b">${escapeHtml(s.headline)}</p>
        <p style="margin:2px 0 0;color:#94a3b8;font-size:12px">${result.itemsScanned.toLocaleString()} items scanned · ${counts}</p></td>
      <td style="text-align:right;width:80px">
        <div style="display:inline-block;border:2px solid ${gradeColor};color:${gradeColor};border-radius:12px;width:64px;height:64px;line-height:1">
          <div style="font-size:30px;font-weight:900;margin-top:12px">${s.grade}</div>
          <div style="font-size:10px">${s.score}/100</div></div></td>
    </tr></table>
    <table style="width:100%;border-collapse:collapse;margin-top:16px">${rows || `<tr><td style="padding:16px;color:#059669">No oversharing found in the scanned items.</td></tr>`}</table>
    <p style="margin-top:20px;color:#94a3b8;font-size:12px;text-align:center">Generated by OverShare Check · oversharecheck.com</p>
  </div>`;
}

export async function sendReportEmail(to: string, result: ScanResult): Promise<void> {
  const s = summarize(result);
  await sendMail({
    to,
    subject: `Exposure report: ${result.siteName} — Grade ${s.grade} (${result.findings.length} findings)`,
    html: reportHtml(result),
  });
}

/* ---------------------------------------------------------------- Teams --- */

function adaptiveCard(result: ScanResult) {
  const s = summarize(result);
  const gradeColor = { A: "good", B: "good", C: "warning", D: "warning", F: "attention" }[s.grade];

  return {
    type: "AdaptiveCard",
    $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
    version: "1.4",
    body: [
      {
        type: "TextBlock",
        text: "OverShare Check · Exposure Report",
        weight: "Bolder",
        color: "Accent",
        size: "Small",
        isSubtle: true,
      },
      {
        type: "ColumnSet",
        columns: [
          {
            type: "Column",
            width: "stretch",
            items: [
              { type: "TextBlock", text: result.siteName, weight: "Bolder", size: "Large", wrap: true },
              { type: "TextBlock", text: s.headline, wrap: true, spacing: "None", color: "Default" },
            ],
          },
          {
            type: "Column",
            width: "auto",
            items: [
              { type: "TextBlock", text: s.grade, size: "ExtraLarge", weight: "Bolder", color: gradeColor },
              { type: "TextBlock", text: `${s.score}/100`, size: "Small", isSubtle: true, spacing: "None" },
            ],
          },
        ],
      },
      {
        type: "FactSet",
        facts: SEVERITIES.map((sev) => ({
          title: SEVERITY_META[sev].label,
          value: String(s.counts[sev]),
        })),
      },
      ...result.findings.slice(0, 8).map((f) => ({
        type: "TextBlock",
        wrap: true,
        text: `**[${SEVERITY_META[f.severity].label}] ${FINDING_META[f.type].title}** — ${f.detail}`,
        spacing: "Small",
      })),
      {
        type: "TextBlock",
        text: `${result.itemsScanned.toLocaleString()} items scanned · oversharecheck.com`,
        size: "Small",
        isSubtle: true,
        wrap: true,
      },
    ],
  };
}

/** POST an Adaptive Card to a Teams Workflows incoming webhook. */
export async function postReportToTeams(webhookUrl: string, result: ScanResult): Promise<void> {
  // Defense in depth — the route validates too, but never trust the caller.
  if (!isValidTeamsWebhook(webhookUrl)) {
    throw new Error("Refusing to post: URL is not an allowed Teams webhook host.");
  }
  const res = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      type: "message",
      attachments: [
        {
          contentType: "application/vnd.microsoft.card.adaptive",
          content: adaptiveCard(result),
        },
      ],
    }),
  });
  if (!res.ok) throw new Error(`Teams post failed: ${res.status} ${await res.text()}`);
}

/* ----------------------------------------------------------------- util --- */

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
}
